name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Vérifie l'arborescence du répertoire
    - name: List files in the directory
      run: ls -R

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file collab-api/pom.xml

    - name: Run tests
      run: mvn test --file collab-api/pom.xml  # Exécution des tests
      
    - name: Upload JAR
      uses: actions/upload-artifact@v4
      with:
        name: collab-api-jar
        path: collab-api/target/collab-api-0.0.1-SNAPSHOT.jar

  docker-build:
    needs: build  # S'assure que le job docker s'exécute après le job build Maven
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Download JAR artifact
      uses: actions/download-artifact@v4
      with:
        name: collab-api-jar
        path: collab-api/target

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    # Login DockerHub - Déplace cette étape avant la construction de l'image
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker buildx build \
          --file collab-api/Dockerfile \
          --tag syphaxlch/collab-api:${{ github.sha }} \
          --load \ 
          collab-api  # Utilisation du commit SHA comme tag unique

    - name: Push Docker image
      run: |
        docker push my-image-name:${{ github.sha }}  # Pousser avec le tag basé sur le commit SHA
